/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 12 03:26:33 GMT 2021
 */

package com.group9.bankofaz.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.group9.bankofaz.exception.EmployeeListException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmployeeListException_ESTest extends EmployeeListException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmployeeListException employeeListException0 = new EmployeeListException();
      EmployeeListException employeeListException1 = null;
      try {
        employeeListException1 = new EmployeeListException("", employeeListException0, false, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmployeeListException employeeListException0 = new EmployeeListException();
      EmployeeListException employeeListException1 = new EmployeeListException("3)>tR7I]!bKU", employeeListException0, true, true);
      assertFalse(employeeListException1.equals((Object)employeeListException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      EmployeeListException employeeListException0 = new EmployeeListException(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EmployeeListException employeeListException0 = new EmployeeListException();
      EmployeeListException employeeListException1 = new EmployeeListException("3)>tR7I]!bKU", employeeListException0);
      assertFalse(employeeListException1.equals((Object)employeeListException0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EmployeeListException employeeListException0 = new EmployeeListException("*J");
  }
}
