/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 12 03:24:27 GMT 2021
 */

package com.group9.bankofaz.component;

import org.junit.Test;
import static org.junit.Assert.*;
import com.group9.bankofaz.component.VerifyRecaptcha;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VerifyRecaptcha_ESTest extends VerifyRecaptcha_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = VerifyRecaptcha.verify("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = VerifyRecaptcha.verify("^");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = VerifyRecaptcha.verify((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VerifyRecaptcha verifyRecaptcha0 = new VerifyRecaptcha();
  }
}
