/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 12 03:42:31 GMT 2021
 */

package com.group9.bankofaz.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.group9.bankofaz.model.BankAccount;
import com.group9.bankofaz.model.ExternalUser;
import com.group9.bankofaz.model.Pii;
import com.group9.bankofaz.model.Users;
import com.group9.bankofaz.service.RegistrationServiceImpl;
import java.security.KeyPair;
import java.security.PrivateKey;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegistrationServiceImpl_ESTest extends RegistrationServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      KeyPair keyPair0 = registrationServiceImpl0.generateKeyPair();
      assertNotNull(keyPair0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      Pii pii0 = new Pii();
      // Undeclared exception!
      try { 
        registrationServiceImpl0.addPii(pii0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.RegistrationServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      // Undeclared exception!
      try { 
        registrationServiceImpl0.userIfExistsFromAllUsers("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.RegistrationServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      String string0 = registrationServiceImpl0.getPrivateKeyLocation((String) null);
      assertEquals("C:\\Users\\125164\\AppData\\Local\\Temp\\3\\/null", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      String string0 = registrationServiceImpl0.getVisaStatus();
      //  // Unstable assertion: assertNotNull(string0);
      //  // Unstable assertion: assertEquals("L2", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      // Undeclared exception!
      try { 
        registrationServiceImpl0.userIfExists(" bankaccount ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.RegistrationServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      ExternalUser externalUser0 = new ExternalUser();
      PrivateKey privateKey0 = registrationServiceImpl0.addExternalUser(externalUser0);
      // Undeclared exception!
      try { 
        registrationServiceImpl0.generateTemporaryKeyFile(privateKey0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Prefix string too short
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      Users users0 = new Users();
      // Undeclared exception!
      try { 
        registrationServiceImpl0.addLoginInfo(users0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.RegistrationServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      BankAccount bankAccount0 = new BankAccount();
      // Undeclared exception!
      try { 
        registrationServiceImpl0.addBankAccount(bankAccount0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.RegistrationServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      RegistrationServiceImpl registrationServiceImpl0 = new RegistrationServiceImpl();
      // Undeclared exception!
      try { 
        registrationServiceImpl0.externalUserWithSSNExists("Ak+AVA;Y|(VYigMem+9");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.RegistrationServiceImpl", e);
      }
  }
}
