/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 12 03:47:32 GMT 2021
 */

package com.group9.bankofaz.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.group9.bankofaz.model.BankAccount;
import com.group9.bankofaz.model.Transaction;
import com.group9.bankofaz.service.TransactionManagerImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TransactionManagerImpl_ESTest extends TransactionManagerImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      BankAccount bankAccount0 = new BankAccount();
      transaction0.setFromacc(bankAccount0);
      // Undeclared exception!
      try { 
        transactionManagerImpl0.performTransaction(transaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      transaction0.setAmt(4531.5054F);
      transaction0.setTransType(" email : ");
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      try { 
        transactionManagerImpl0.submitTransaction(transaction0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Transaction not allowed
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      // Undeclared exception!
      try { 
        transactionManagerImpl0.submitTransaction(transaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      // Undeclared exception!
      try { 
        transactionManagerImpl0.scheduleTask();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      // Undeclared exception!
      try { 
        transactionManagerImpl0.initIt();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/context/ApplicationContext
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      // Undeclared exception!
      try { 
        transactionManagerImpl0.updateEmployeeList();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      transaction0.setTransStatus("kbu\"L");
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      transactionManagerImpl0.cancelTransaction(transaction0);
      // Undeclared exception!
      try { 
        Injector.executePostConstruct((Object) transactionManagerImpl0, (Class<?>) TransactionManagerImpl.class);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to execute @PostConstructor in com.group9.bankofaz.service.TransactionManagerImpl
         //
         verifyException("org.evosuite.runtime.javaee.injection.Injector", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      transaction0.setTransStatus("pending");
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      // Undeclared exception!
      try { 
        transactionManagerImpl0.cancelTransaction(transaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      transaction0.setTransStatus("+H20p(@[");
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      // Undeclared exception!
      try { 
        transactionManagerImpl0.updateTransaction(transaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      transaction0.setAmt((-2510.6082F));
      transaction0.setTransType(" email : ");
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      try { 
        transactionManagerImpl0.submitTransaction(transaction0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Transaction not allowed
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Transaction transaction0 = new Transaction();
      transaction0.setTransType(" email : ");
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      try { 
        transactionManagerImpl0.submitTransaction(transaction0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Transaction not allowed
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TransactionManagerImpl transactionManagerImpl0 = new TransactionManagerImpl();
      // Undeclared exception!
      try { 
        transactionManagerImpl0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.group9.bankofaz.service.TransactionManagerImpl", e);
      }
  }
}
